server:
  host: 127.0.0.1
  port: 1111
  size: 128
  netty:
    boss-count: 1
    worker-count: 5
    keep-alive: true
    backlog: 10
  ssl:
    value: false

#https://stackoverflow.com/questions/43574234/how-to-prevent-embedded-netty-server-from-starting-with-spring-boot-starter-webf
#진짜 찾는다고 개고생했다
spring.main.web-application-type: none